[profile.default]
solc = "0.8.23"
ffi = true
src = "src"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
